### PR TITLE
fix signature validation issue

### LINKED ISSUE #275: `Signature validation failed. SAML Response rejected` error
Here is my SAML response:

```
<samlp:Response 
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" 
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" 
    ID="pfx044be614-1999-e599-4726-5e0d6868e5ff" 
    Version="2.0" 
    IssueInstant="2020-09-01T15:59:44Z" 
    Destination="http://localhost:8080/saml-demo/acs.jsp" 
    InResponseTo="ONELOGIN_6a5024aa-e247-43a4-9951-27282d8f406d">
    <saml:Issuer>https://app.onelogin.com/saml/metadata/60a512d0-8c8e-4d6e-be69-102fa7693c9c</saml:Issuer>
    <ds:Signature 
        xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod 
                Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <ds:SignatureMethod 
                Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
            <ds:Reference 
                URI="#pfx044be614-1999-e599-4726-5e0d6868e5ff">
                <ds:Transforms>
                    <ds:Transform 
                        Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform 
                        Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </ds:Transforms>
                <ds:DigestMethod 
                    Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <ds:DigestValue>f9iSqAvFnQkrdV+
                    mLYWFOK2ovGRmwIPlmwrR1YFibog=
                </ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>jUHclAiySjbPJeQAuM93o1Pos8TuGBRLWAQxsAIq2aYsGhuG0MaNhGNQQw4quBA28TQHBtL7rLttKIZaoCUfI2P7QpJ177xLpCM5EvmLIEElado7b7cpuCMMWeIjreNmLAkkPgYR3YM97V8p8++Q/S1gXOUtlzHlPjQIH/KAeo6WNe6UqaY7nahlitRgRM8s+flwT9J7z5FmLqum3kWc3J5jKM3jUkWg41Yv5PGvqcJJmROm8mNZgAgutX09e3VAIvD6Cd3ZGV37n+e1Fmv/Fieg8Vz+9qWqH+4/
            WlJNuTq31Jt1l8sxipWVFZIybxXhUgMSkl8ieF1xkKrYnPRAGg==
        </ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate>MIID2DCCAsCgAwIBAgIUGMtzUeh2Uu5rMYF5jjN1NyB8fdMwDQYJKoZIhvcNAQEFBQAwRDEPMA0GA1UECgwGTWVldHVwMRUwEwYDVQQLDAxPbmVMb2dpbiBJZFAxGjAYBgNVBAMMEU9uZUxvZ2luIEFjY291bnQgMB4XDTIwMDgzMTE5NDAyMloXDTI1MDgzMTE5NDAyMlowRDEPMA0GA1UECgwGTWVldHVwMRUwEwYDVQQLDAxPbmVMb2dpbiBJZFAxGjAYBgNVBAMMEU9uZUxvZ2luIEFjY291bnQgMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0toZiVL6IEREFS7Q/GN2y74S+XyZs9kD9878j/s9NPHHxf7bjyCbcLzjZQWbnwirOVy9tqAlTgh2Iu8gl87MtvuDRtKFo4JQvrbB7BQqhQUwXffHg3vuxE94K6d8cAHhc08nc4i11PtFChqkB7Hft9iHlVGzHU7p4QDjSvxuIMmEBMxkepn9f47tRg8hqMHHApcFlmtxhKrKst3quK8yQBTsmjJB+mNgVIBiZnrgvcNIqV+sZJPZD7cwky2DbzYe+QWdcoth2W5PaNg+gSruGhbNGZJFNa0V41KpFv6aZDbsInVmREjCgbJb2YINntJPLjXI8RLiwOXT8MnvtazrTwIDAQABo4HBMIG+MAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFHnAxISbvX+fVeFNZBoaXh6Ui+I2MH8GA1UdIwR4MHaAFHnAxISbvX+fVeFNZBoaXh6Ui+I2oUikRjBEMQ8wDQYDVQQKDAZNZWV0dXAxFTATBgNVBAsMDE9uZUxvZ2luIElkUDEaMBgGA1UEAwwRT25lTG9naW4gQWNjb3VudCCCFBjLc1HodlLuazGBeY4zdTcgfH3TMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQUFAAOCAQEAwtmGDWU0V8nwkFn2l0GUmjcguq9iL8otYxYXe+jjyAUEMtpihRPXJ7yZZZmsn5uG+K5/Jfa0V9D22wsS4/ZQyIORjYKO5f9GkSbMbWAVHks3t9jCeInIuhXWqMQLSOPJz0L1vfl4TVAB5G9tBHM4sLzIj6RX+OYz6C6r2b//yQYOFmRndOHnERX5HNqif7K37EyeJHk+QJb7opC7CRBp2SCMy+XfVS6j54CdT+TziSHUzbBlM8QJ/Smd8EkU5aeBVrEarpaAdEUs7K6YtnFRcQdx3QkH9pkJ9wBvldYR8hXnxR54uSXPvbrN+3n5sxPzo11RW/6ge+
                    YUhFcUFRoiAA==
                </ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>
    <samlp:Status>
        <samlp:StatusCode 
            Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
    </samlp:Status>
    <saml:Assertion 
        xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" 
        xmlns:xs="http://www.w3.org/2001/XMLSchema" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        Version="2.0" 
        ID="A1599a65fc5885469e036bed430eb5728c5a9255a" 
        IssueInstant="2020-09-01T15:59:44Z">
        <saml:Issuer>https://app.onelogin.com/saml/metadata/60a512d0-8c8e-4d6e-be69-102fa7693c9c</saml:Issuer>
        <saml:Subject>
            <saml:NameID 
                Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">rui@meetup.com
            </saml:NameID>
            <saml:SubjectConfirmation 
                Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml:SubjectConfirmationData 
                    NotOnOrAfter="2020-09-01T16:02:44Z" 
                    Recipient="http://localhost:8080/saml-demo/acs.jsp" 
                    InResponseTo="ONELOGIN_6a5024aa-e247-43a4-9951-27282d8f406d"/>
            </saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions 
            NotBefore="2020-09-01T15:56:44Z" 
            NotOnOrAfter="2020-09-01T16:02:44Z">
            <saml:AudienceRestriction>
                <saml:Audience>http://localhost:8080/saml-demo/metadata.jsp</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement 
            AuthnInstant="2020-09-01T15:59:43Z" 
            SessionNotOnOrAfter="2020-09-02T15:59:44Z" 
            SessionIndex="_3c6cd52b-c301-40c7-8cfe-8d11816dc61c">
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
            </saml:AuthnContext>
        </saml:AuthnStatement>
    </saml:Assertion>
</samlp:Response>
```

I am able to see the same error in `https://www.samltool.com/validate_response.php`, but I could not figure out which part fell apart.

test connector metadata

```
idp entityid: https://app.onelogin.com/saml/metadata/60a512d0-8c8e-4d6e-be69-102fa7693c9c
sp entityid: http://localhost:8080/saml-demo/metadata.jsp
sp acs url: http://localhost:8080/saml-demo/acs.jsp
homepage: http://localhost:8080/saml-demo/
```

here is the screenshot:
image

### PR DESCRIPTION
**Pull request by chenrui333**
fixes #275

### CODE REVIEW

File: core/src/main/java/com/onelogin/saml2/util/Util.java [hunk 1]
```diff
@@ -597,9 +597,9 @@ public static String calculateX509Fingerprint(X509Certificate x509cert, String a
 			byte[] dataBytes = x509cert.getEncoded();
 			if (alg == null || alg.isEmpty() || alg.equals("SHA-1")|| alg.equals("sha1")) {
 				fingerprint = DigestUtils.sha1Hex(dataBytes);
-			} else if (alg.equals("SHA-256") || alg .equals("sha256")) {
```
Comment (chenrui333) [inline core/src/main/java/com/onelogin/saml2/util/Util.java:600]: @pitbulk I have already tested in my local, that this does fix for my fingerprint validation check.

**Comment by chenrui333** [comment]
Thanks @pitbulk!
